const sources = [
  {
    "id": "nyt",
    "name": "New York Times",
    "flag": "🇺🇸",
    "country": "United States",
    "city": "New York",
    "lat": 34.05,
    "lon": -82.44,
    "lean": "left",
    "lang": "en",
    "rssUrl": "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
    "website": "https://rss.nytimes.com"
  },
  {
    "id": "washpost",
    "name": "Washington Post",
    "flag": "🇺🇸",
    "country": "United States",
    "city": "Washington D.C.",
    "lat": 35.7,
    "lon": -81.81,
    "lean": "left",
    "lang": "en",
    "rssUrl": "https://feeds.washingtonpost.com/rss/world",
    "website": "https://feeds.washingtonpost.com"
  },
  {
    "id": "cnn",
    "name": "CNN",
    "flag": "🇺🇸",
    "country": "United States",
    "city": "Atlanta",
    "lat": 39.74,
    "lon": -85.02,
    "lean": "left",
    "lang": "en",
    "rssUrl": "https://rss.cnn.com/rss/edition.rss",
    "website": "https://rss.cnn.com"
  },
  {
    "id": "foxnews",
    "name": "Fox News",
    "flag": "🇺🇸",
    "country": "United States",
    "city": "New York",
    "lat": 40.2,
    "lon": -73.2,
    "lean": "right",
    "lang": "en",
    "rssUrl": "https://feeds.foxnews.com/foxnews/latest",
    "website": "https://foxnews.com"
  },
  {
    "id": "ap",
    "name": "Associated Press",
    "flag": "🇺🇸",
    "country": "United States",
    "city": "New York",
    "lat": 40.5,
    "lon": -74.2,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://news.google.com/rss/search?q=source:%22Associated%20Press%22&hl=en-US&gl=US&ceid=US:en",
    "website": "https://apnews.com"
  },
  {
    "id": "usatoday",
    "name": "USA Today",
    "flag": "🇺🇸",
    "country": "United States",
    "city": "McLean, VA",
    "lat": 38.4,
    "lon": -78,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.usatoday.com/rss/news/",
    "website": "https://usatoday.com"
  },
  {
    "id": "latimes",
    "name": "Los Angeles Times",
    "flag": "🇺🇸",
    "country": "United States",
    "city": "Los Angeles",
    "lat": 35.57,
    "lon": -119.19,
    "lean": "left",
    "lang": "en",
    "rssUrl": "https://www.latimes.com/rss2.0.xml",
    "website": "https://www.latimes.com"
  },
  {
    "id": "newsmax",
    "name": "Newsmax",
    "flag": "🇺🇸",
    "country": "United States",
    "city": "West Palm Beach",
    "lat": 26.7,
    "lon": -80.1,
    "lean": "right",
    "lang": "en",
    "rssUrl": "https://www.newsmax.com/rss/News/1/",
    "website": "https://newsmax.com"
  },
  {
    "id": "folha",
    "name": "Folha de S.Paulo",
    "flag": "🇧🇷",
    "country": "Brazil",
    "city": "São Paulo",
    "lat": -23,
    "lon": -47.5,
    "lean": "center",
    "lang": "pt",
    "rssUrl": "https://feeds.folha.uol.com.br/emcimadahora/rss091.xml",
    "website": "https://folha.uol.com.br"
  },
  {
    "id": "g1",
    "name": "G1 / O Globo",
    "flag": "🇧🇷",
    "country": "Brazil",
    "city": "Rio de Janeiro",
    "lat": -22.9,
    "lon": -43.2,
    "lean": "left",
    "lang": "pt",
    "rssUrl": "https://g1.globo.com/dynamo/paginag1/rss2.xml",
    "website": "https://g1.globo.com"
  },
  {
    "id": "uol",
    "name": "UOL Notícias",
    "flag": "🇧🇷",
    "country": "Brazil",
    "city": "São Paulo",
    "lat": -23.3,
    "lon": -46.5,
    "lean": "center",
    "lang": "pt",
    "rssUrl": "https://noticias.uol.com.br/rss.xml",
    "website": "https://noticias.uol.com.br"
  },
  {
    "id": "estadao",
    "name": "Estadão",
    "flag": "🇧🇷",
    "country": "Brazil",
    "city": "São Paulo",
    "lat": -23.6,
    "lon": -46,
    "lean": "right",
    "lang": "pt",
    "rssUrl": "https://www.estadao.com.br/rss/ultimas-noticias.xml",
    "website": "https://estadao.com.br"
  },
  {
    "id": "correio",
    "name": "Correio Braziliense",
    "flag": "🇧🇷",
    "country": "Brazil",
    "city": "Brasília",
    "lat": -15.8,
    "lon": -47.9,
    "lean": "center",
    "lang": "pt",
    "rssUrl": "https://www.correiobraziliense.com.br/rss_feed.xml",
    "website": "https://correiobraziliense.com.br"
  },
  {
    "id": "jovempan",
    "name": "Jovem Pan News",
    "flag": "🇧🇷",
    "country": "Brazil",
    "city": "São Paulo",
    "lat": -22.57,
    "lon": -45.92,
    "lean": "right",
    "lang": "pt",
    "rssUrl": "https://jovempan.com.br/feed",
    "website": "https://jovempan.com.br"
  },
  {
    "id": "clarin",
    "name": "Clarín",
    "flag": "🇦🇷",
    "country": "Argentina",
    "city": "Buenos Aires",
    "lat": -35.01,
    "lon": -58.89,
    "lean": "right",
    "lang": "es",
    "rssUrl": "https://www.clarin.com/rss/lo-ultimo/",
    "website": "https://www.clarin.com"
  },
  {
    "id": "lanacion",
    "name": "La Nación",
    "flag": "🇦🇷",
    "country": "Argentina",
    "city": "Buenos Aires",
    "lat": -34.8,
    "lon": -58,
    "lean": "right",
    "lang": "es",
    "rssUrl": "https://www.lanacion.com.ar/arc/outboundfeeds/rss/",
    "website": "https://lanacion.com.ar"
  },
  {
    "id": "eluniversal",
    "name": "El Universal",
    "flag": "🇲🇽",
    "country": "Mexico",
    "city": "Mexico City",
    "lat": 19.8,
    "lon": -99.5,
    "lean": "center",
    "lang": "es",
    "rssUrl": "https://www.eluniversal.com.mx/rss/portada.xml",
    "website": "https://eluniversal.com.mx"
  },
  {
    "id": "milenio",
    "name": "Milenio",
    "flag": "🇲🇽",
    "country": "Mexico",
    "city": "Mexico City",
    "lat": 19.1,
    "lon": -98.8,
    "lean": "right",
    "lang": "es",
    "rssUrl": "https://www.milenio.com/rss/noticias.xml",
    "website": "https://milenio.com"
  },
  {
    "id": "eltiempo",
    "name": "El Tiempo",
    "flag": "🇨🇴",
    "country": "Colombia",
    "city": "Bogotá",
    "lat": 4.7,
    "lon": -74.1,
    "lean": "center",
    "lang": "es",
    "rssUrl": "https://www.eltiempo.com/rss/portada.xml",
    "website": "https://eltiempo.com"
  },
  {
    "id": "elcomercio",
    "name": "El Comercio",
    "flag": "🇵🇪",
    "country": "Peru",
    "city": "Lima",
    "lat": -12.04,
    "lon": -77.03,
    "lean": "right",
    "lang": "es",
    "rssUrl": "https://elcomercio.pe/feed/",
    "website": "https://elcomercio.pe"
  },
  {
    "id": "bbc",
    "name": "BBC News",
    "flag": "🇬🇧",
    "country": "United Kingdom",
    "city": "London",
    "lat": 53,
    "lon": -2,
    "lean": "center",
    "lang": "en",
    "rssUrl": "http://feeds.bbci.co.uk/news/rss.xml",
    "website": "https://bbc.com/news"
  },
  {
    "id": "guardian",
    "name": "The Guardian",
    "flag": "🇬🇧",
    "country": "United Kingdom",
    "city": "London",
    "lat": 51.3,
    "lon": 0.5,
    "lean": "left",
    "lang": "en",
    "rssUrl": "https://www.theguardian.com/uk/rss",
    "website": "https://theguardian.com"
  },
  {
    "id": "telegraph",
    "name": "The Telegraph",
    "flag": "🇬🇧",
    "country": "United Kingdom",
    "city": "London",
    "lat": 51.5,
    "lon": 1.2,
    "lean": "right",
    "lang": "en",
    "rssUrl": "https://www.telegraph.co.uk/rss.xml",
    "website": "https://telegraph.co.uk"
  },
  {
    "id": "reuters",
    "name": "Reuters",
    "flag": "🌐",
    "country": "United Kingdom",
    "city": "London",
    "lat": 51,
    "lon": -1.2,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://news.google.com/rss/search?q=source:%22Reuters%22&hl=en-US&gl=US&ceid=US:en",
    "website": "https://reuters.com"
  },
  {
    "id": "lemonde",
    "name": "Le Monde",
    "flag": "🇫🇷",
    "country": "France",
    "city": "Paris",
    "lat": 49.3,
    "lon": 2,
    "lean": "left",
    "lang": "fr",
    "rssUrl": "https://www.lemonde.fr/rss/une.xml",
    "website": "https://lemonde.fr"
  },
  {
    "id": "lefigaro",
    "name": "Le Figaro",
    "flag": "🇫🇷",
    "country": "France",
    "city": "Paris",
    "lat": 48.8,
    "lon": 2.8,
    "lean": "right",
    "lang": "fr",
    "rssUrl": "https://www.lefigaro.fr/rss/figaro_actualites.xml",
    "website": "https://lefigaro.fr"
  },
  {
    "id": "france24",
    "name": "France 24",
    "flag": "🌐",
    "country": "France",
    "city": "Paris",
    "lat": 48.07,
    "lon": -0.15,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.france24.com/en/rss",
    "website": "https://www.france24.com"
  },
  {
    "id": "afp",
    "name": "AFP",
    "flag": "🇫🇷",
    "country": "France",
    "city": "Paris",
    "lat": 48.6,
    "lon": 1.8,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://news.google.com/rss/search?q=source:%22AFP%22&hl=en-US&gl=US&ceid=US:en",
    "website": "https://afp.com"
  },
  {
    "id": "spiegel",
    "name": "Der Spiegel",
    "flag": "🇩🇪",
    "country": "Germany",
    "city": "Hamburg",
    "lat": 53.7,
    "lon": 9.6,
    "lean": "left",
    "lang": "de",
    "rssUrl": "https://www.spiegel.de/schlagzeilen/index.rss",
    "website": "https://spiegel.de"
  },
  {
    "id": "zeit",
    "name": "Die Zeit",
    "flag": "🇩🇪",
    "country": "Germany",
    "city": "Hamburg",
    "lat": 53.4,
    "lon": 10.2,
    "lean": "left",
    "lang": "de",
    "rssUrl": "https://newsfeed.zeit.de/all",
    "website": "https://zeit.de"
  },
  {
    "id": "dw",
    "name": "Deutsche Welle",
    "flag": "🇩🇪",
    "country": "Germany",
    "city": "Bonn",
    "lat": 50.7,
    "lon": 7.1,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://rss.dw.com/rdf/rss-en-all",
    "website": "https://dw.com"
  },
  {
    "id": "elpais",
    "name": "El País",
    "flag": "🇪🇸",
    "country": "Spain",
    "city": "Madrid",
    "lat": 40.7,
    "lon": -4,
    "lean": "left",
    "lang": "es",
    "rssUrl": "https://feeds.elpais.com/mrss-s/pages/ep/site/elpais.com/portada",
    "website": "https://elpais.com"
  },
  {
    "id": "elmundo",
    "name": "El Mundo",
    "flag": "🇪🇸",
    "country": "Spain",
    "city": "Madrid",
    "lat": 40.2,
    "lon": -3.4,
    "lean": "right",
    "lang": "es",
    "rssUrl": "https://e00-elmundo.uecdn.es/elmundo/rss/portada.xml",
    "website": "https://elmundo.es"
  },
  {
    "id": "repubblica",
    "name": "La Repubblica",
    "flag": "🇮🇹",
    "country": "Italy",
    "city": "Rome",
    "lat": 41.9,
    "lon": 12.5,
    "lean": "left",
    "lang": "it",
    "rssUrl": "https://www.repubblica.it/rss/homepage/rss2.0.xml",
    "website": "https://repubblica.it"
  },
  {
    "id": "corriere",
    "name": "Corriere della Sera",
    "flag": "🇮🇹",
    "country": "Italy",
    "city": "Milan",
    "lat": 45.5,
    "lon": 9.2,
    "lean": "center",
    "lang": "it",
    "rssUrl": "https://www.corriere.it/rss/homepage.xml",
    "website": "https://corriere.it"
  },
  {
    "id": "publico",
    "name": "Público",
    "flag": "🇵🇹",
    "country": "Portugal",
    "city": "Lisbon",
    "lat": 39,
    "lon": -9.4,
    "lean": "left",
    "lang": "pt",
    "rssUrl": "https://www.publico.pt/rss",
    "website": "https://publico.pt"
  },
  {
    "id": "expresso",
    "name": "Expresso",
    "flag": "🇵🇹",
    "country": "Portugal",
    "city": "Lisbon",
    "lat": 38.5,
    "lon": -8.9,
    "lean": "right",
    "lang": "pt",
    "rssUrl": "https://expresso.pt/rss",
    "website": "https://expresso.pt"
  },
  {
    "id": "nos",
    "name": "NOS Nieuws",
    "flag": "🇳🇱",
    "country": "Netherlands",
    "city": "Hilversum",
    "lat": 52.2,
    "lon": 5.2,
    "lean": "center",
    "lang": "nl",
    "rssUrl": "https://feeds.nos.nl/nosnieuwsalgemeen",
    "website": "https://nos.nl"
  },
  {
    "id": "euronews",
    "name": "Euronews",
    "flag": "🌐",
    "country": "France",
    "city": "Lyon",
    "lat": 45.8,
    "lon": 4.8,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.euronews.com/rss",
    "website": "https://euronews.com"
  },
  {
    "id": "timesofindia",
    "name": "Times of India",
    "flag": "🇮🇳",
    "country": "India",
    "city": "Mumbai",
    "lat": 19.1,
    "lon": 72.9,
    "lean": "right",
    "lang": "en",
    "rssUrl": "https://timesofindia.indiatimes.com/rssfeedstopstories.cms",
    "website": "https://timesofindia.com"
  },
  {
    "id": "hindustantimes",
    "name": "Hindustan Times",
    "flag": "🇮🇳",
    "country": "India",
    "city": "New Delhi",
    "lat": 27.12,
    "lon": 74.95,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml",
    "website": "https://www.hindustantimes.com"
  },
  {
    "id": "japantimes",
    "name": "The Japan Times",
    "flag": "🇯🇵",
    "country": "Japan",
    "city": "Tokyo",
    "lat": 36.3,
    "lon": 138.8,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.japantimes.co.jp/feed/",
    "website": "https://japantimes.co.jp"
  },
  {
    "id": "nhk",
    "name": "NHK World",
    "flag": "🇯🇵",
    "country": "Japan",
    "city": "Tokyo",
    "lat": 35.7,
    "lon": 140.2,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www3.nhk.or.jp/nhkworld/en/news/news.xml",
    "website": "https://nhk.or.jp/nhkworld"
  },
  {
    "id": "sankei",
    "name": "Sankei Shimbun",
    "flag": "🇯🇵",
    "country": "Japan",
    "city": "Tokyo",
    "lat": 35.1,
    "lon": 139.5,
    "lean": "right",
    "lang": "ja",
    "rssUrl": "https://www.sankei.com/rss/",
    "website": "https://sankei.com"
  },
  {
    "id": "scmp",
    "name": "South China Morning Post",
    "flag": "🇭🇰",
    "country": "Hong Kong",
    "city": "Hong Kong",
    "lat": 22.3,
    "lon": 114.2,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.scmp.com/rss/91/feed",
    "website": "https://scmp.com"
  },
  {
    "id": "straitstimes",
    "name": "The Straits Times",
    "flag": "🇸🇬",
    "country": "Singapore",
    "city": "Singapore",
    "lat": 1.4,
    "lon": 103.8,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.straitstimes.com/news/asia/rss.xml",
    "website": "https://straitstimes.com"
  },
  {
    "id": "koreaherald",
    "name": "Korea Herald",
    "flag": "🇰🇷",
    "country": "South Korea",
    "city": "Seoul",
    "lat": 37.6,
    "lon": 127,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.koreaherald.com/rss/top_news_list.xml",
    "website": "https://koreaherald.com"
  },
  {
    "id": "bangkokpost",
    "name": "Bangkok Post",
    "flag": "🇹🇭",
    "country": "Thailand",
    "city": "Bangkok",
    "lat": 13.8,
    "lon": 100.5,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.bangkokpost.com/rss/data/topstories.xml",
    "website": "https://bangkokpost.com"
  },
  {
    "id": "dawn",
    "name": "Dawn",
    "flag": "🇵🇰",
    "country": "Pakistan",
    "city": "Karachi",
    "lat": 24.9,
    "lon": 67,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.dawn.com/rss/home",
    "website": "https://dawn.com"
  },
  {
    "id": "abcau",
    "name": "ABC News Australia",
    "flag": "🇦🇺",
    "country": "Australia",
    "city": "Sydney",
    "lat": -33.2,
    "lon": 150.6,
    "lean": "left",
    "lang": "en",
    "rssUrl": "https://www.abc.net.au/news/feed/51120/rss.xml",
    "website": "https://abc.net.au/news"
  },
  {
    "id": "skynewsau",
    "name": "Sky News Australia",
    "flag": "🇦🇺",
    "country": "Australia",
    "city": "Sydney",
    "lat": -34.5,
    "lon": 151.2,
    "lean": "right",
    "lang": "en",
    "rssUrl": "https://www.skynews.com.au/rss.xml",
    "website": "https://skynews.com.au"
  },
  {
    "id": "aljazeera",
    "name": "Al Jazeera",
    "flag": "🇶🇦",
    "country": "Qatar",
    "city": "Doha",
    "lat": 25.3,
    "lon": 51.5,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.aljazeera.com/xml/rss/all.xml",
    "website": "https://aljazeera.com"
  },
  {
    "id": "arabnews",
    "name": "Arab News",
    "flag": "🇸🇦",
    "country": "Saudi Arabia",
    "city": "Riyadh",
    "lat": 24.7,
    "lon": 46.7,
    "lean": "right",
    "lang": "en",
    "rssUrl": "https://www.arabnews.com/rss.xml",
    "website": "https://arabnews.com"
  },
  {
    "id": "haaretz",
    "name": "Haaretz",
    "flag": "🇮🇱",
    "country": "Israel",
    "city": "Tel Aviv",
    "lat": 32.1,
    "lon": 34.8,
    "lean": "left",
    "lang": "en",
    "rssUrl": "https://www.haaretz.com/cmlink/1.628765",
    "website": "https://haaretz.com"
  },
  {
    "id": "dailynation",
    "name": "Daily Nation",
    "flag": "🇰🇪",
    "country": "Kenya",
    "city": "Nairobi",
    "lat": -1.3,
    "lon": 36.8,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://nation.africa/kenya/rss.xml",
    "website": "https://nation.africa"
  },
  {
    "id": "mailguardian",
    "name": "Mail & Guardian",
    "flag": "🇿🇦",
    "country": "South Africa",
    "city": "Johannesburg",
    "lat": -26.2,
    "lon": 28,
    "lean": "left",
    "lang": "en",
    "rssUrl": "https://mg.co.za/feed/",
    "website": "https://mg.co.za"
  },
  {
    "id": "cnnbr",
    "name": "CNN Brasil",
    "flag": "🇧🇷",
    "country": "Brazil",
    "city": "São Paulo",
    "lat": -23.3,
    "lon": -46.8,
    "lean": "center",
    "lang": "pt",
    "rssUrl": "https://www.cnnbrasil.com.br/feed/",
    "website": "https://cnnbrasil.com.br"
  },
  {
    "id": "r7",
    "name": "R7 Notícias",
    "flag": "🇧🇷",
    "country": "Brazil",
    "city": "São Paulo",
    "lat": -23.6,
    "lon": -47.2,
    "lean": "center",
    "lang": "pt",
    "rssUrl": "https://noticias.r7.com/feed.xml",
    "website": "https://r7.com"
  },
  {
    "id": "gazetadopovo",
    "name": "Gazeta do Povo",
    "flag": "🇧🇷",
    "country": "Brazil",
    "city": "Curitiba",
    "lat": -25.4,
    "lon": -49.3,
    "lean": "right",
    "lang": "pt",
    "rssUrl": "https://www.gazetadopovo.com.br/feed/",
    "website": "https://gazetadopovo.com.br"
  },
  {
    "id": "terra",
    "name": "Terra Notícias",
    "flag": "🇧🇷",
    "country": "Brazil",
    "city": "São Paulo",
    "lat": -23.1,
    "lon": -46.3,
    "lean": "center",
    "lang": "pt",
    "rssUrl": "https://www.terra.com.br/rss/noticias/",
    "website": "https://terra.com.br"
  },
  {
    "id": "band",
    "name": "Band News",
    "flag": "🇧🇷",
    "country": "Brazil",
    "city": "São Paulo",
    "lat": -23.7,
    "lon": -46.1,
    "lean": "center",
    "lang": "pt",
    "rssUrl": "https://www.band.uol.com.br/rss/noticias.xml",
    "website": "https://band.uol.com.br"
  },
  {
    "id": "infobae",
    "name": "Infobae",
    "flag": "🇦🇷",
    "country": "Argentina",
    "city": "Buenos Aires",
    "lat": -34.5,
    "lon": -58.4,
    "lean": "center",
    "lang": "es",
    "rssUrl": "https://www.infobae.com/feeds/rss/",
    "website": "https://infobae.com"
  },
  {
    "id": "elespectador",
    "name": "El Espectador",
    "flag": "🇨🇴",
    "country": "Colombia",
    "city": "Bogotá",
    "lat": 4.4,
    "lon": -74.4,
    "lean": "left",
    "lang": "es",
    "rssUrl": "https://www.elespectador.com/rss/",
    "website": "https://elespectador.com"
  },
  {
    "id": "telesur",
    "name": "TeleSUR",
    "flag": "🇻🇪",
    "country": "Venezuela",
    "city": "Caracas",
    "lat": 10.5,
    "lon": -66.9,
    "lean": "left",
    "lang": "es",
    "rssUrl": "https://www.telesurtv.net/xml/telesur-en.xml",
    "website": "https://telesurtv.net"
  },
  {
    "id": "bbcmundo",
    "name": "BBC Mundo",
    "flag": "🌐",
    "country": "United Kingdom",
    "city": "London",
    "lat": 51.9,
    "lon": -0.3,
    "lean": "center",
    "lang": "es",
    "rssUrl": "https://feeds.bbci.co.uk/mundo/rss.xml",
    "website": "https://bbc.com/mundo"
  },
  {
    "id": "rt",
    "name": "RT News",
    "flag": "🇷🇺",
    "country": "Russia",
    "city": "Moscow",
    "lat": 55.8,
    "lon": 37.6,
    "lean": "right",
    "lang": "en",
    "rssUrl": "https://www.rt.com/rss/news/",
    "website": "https://rt.com"
  },
  {
    "id": "irishtimes",
    "name": "The Irish Times",
    "flag": "🇮🇪",
    "country": "Ireland",
    "city": "Dublin",
    "lat": 53.4,
    "lon": -6.3,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.irishtimes.com/cmlink/news-1.1319192",
    "website": "https://irishtimes.com"
  },
  {
    "id": "rfi",
    "name": "RFI",
    "flag": "🇫🇷",
    "country": "France",
    "city": "Paris",
    "lat": 48.2,
    "lon": 2,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.rfi.fr/en/rss",
    "website": "https://rfi.fr/en"
  },
  {
    "id": "swissinfo",
    "name": "SWI swissinfo",
    "flag": "🇨🇭",
    "country": "Switzerland",
    "city": "Bern",
    "lat": 46.9,
    "lon": 7.4,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.swissinfo.ch/eng/rss/all-news",
    "website": "https://swissinfo.ch"
  },
  {
    "id": "thehindu",
    "name": "The Hindu",
    "flag": "🇮🇳",
    "country": "India",
    "city": "Chennai",
    "lat": 13.71,
    "lon": 76.74,
    "lean": "left",
    "lang": "en",
    "rssUrl": "https://www.thehindu.com/feeder/default.rss",
    "website": "https://www.thehindu.com"
  },
  {
    "id": "trtworld",
    "name": "TRT World",
    "flag": "🇹🇷",
    "country": "Turkey",
    "city": "Istanbul",
    "lat": 41,
    "lon": 29,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.trtworld.com/rss",
    "website": "https://trtworld.com"
  },
  {
    "id": "globaltimes",
    "name": "Global Times",
    "flag": "🇨🇳",
    "country": "China",
    "city": "Beijing",
    "lat": 37.91,
    "lon": 115.29,
    "lean": "left",
    "lang": "en",
    "rssUrl": "https://www.globaltimes.cn/rss/outbrain.xml",
    "website": "https://www.globaltimes.cn"
  },
  {
    "id": "cna",
    "name": "CNA",
    "flag": "🇸🇬",
    "country": "Singapore",
    "city": "Singapore",
    "lat": 2.85,
    "lon": 102.87,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml",
    "website": "https://www.channelnewsasia.com"
  },
  {
    "id": "sbsau",
    "name": "SBS News",
    "flag": "🇦🇺",
    "country": "Australia",
    "city": "Sydney",
    "lat": -33.8,
    "lon": 152,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.sbs.com.au/news/feed",
    "website": "https://sbs.com.au/news"
  },
  {
    "id": "thenational",
    "name": "The National",
    "flag": "🇦🇪",
    "country": "UAE",
    "city": "Abu Dhabi",
    "lat": 24.5,
    "lon": 54.7,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.thenationalnews.com/rss",
    "website": "https://thenationalnews.com"
  },
  {
    "id": "allafrica",
    "name": "AllAfrica",
    "flag": "🌍",
    "country": "South Africa",
    "city": "Cape Town",
    "lat": -32.68,
    "lon": 19.55,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf",
    "website": "https://allafrica.com"
  },
  {
    "id": "punchng",
    "name": "Punch Nigeria",
    "flag": "🇳🇬",
    "country": "Nigeria",
    "city": "Lagos",
    "lat": 6.5,
    "lon": 3.4,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://punchng.com/feed/",
    "website": "https://punchng.com"
  },
  {
    "id": "cbsnews",
    "name": "CBS News",
    "flag": "🇺🇸",
    "country": "United States",
    "city": "New York",
    "lat": 41.5,
    "lon": -73.5,
    "lean": "center",
    "lang": "en",
    "type": "tv",
    "rssUrl": "https://www.cbsnews.com/latest/rss/main",
    "website": "https://cbsnews.com"
  },
  {
    "id": "nbcnews",
    "name": "NBC News",
    "flag": "🇺🇸",
    "country": "United States",
    "city": "New York",
    "lat": 36,
    "lon": -81.5,
    "lean": "left",
    "lang": "en",
    "type": "tv",
    "rssUrl": "https://feeds.nbcnews.com/nbcnews/public/news",
    "website": "https://feeds.nbcnews.com"
  },
  {
    "id": "abcnews",
    "name": "ABC News",
    "flag": "🇺🇸",
    "country": "United States",
    "city": "New York",
    "lat": 41.47,
    "lon": -75.45,
    "lean": "left",
    "lang": "en",
    "type": "tv",
    "rssUrl": "https://abcnews.go.com/abcnews/topstories",
    "website": "https://abcnews.go.com"
  },
  {
    "id": "pbs",
    "name": "PBS NewsHour",
    "flag": "🇺🇸",
    "country": "United States",
    "city": "Arlington, VA",
    "lat": 36.47,
    "lon": -91.68,
    "lean": "center",
    "lang": "en",
    "type": "tv",
    "rssUrl": "https://www.pbs.org/newshour/feeds/rss/headlines",
    "website": "https://www.pbs.org"
  },
  {
    "id": "msnbc",
    "name": "MSNBC",
    "flag": "🇺🇸",
    "country": "United States",
    "city": "New York",
    "lat": 41.1,
    "lon": -73.1,
    "lean": "left",
    "lang": "en",
    "type": "tv",
    "rssUrl": "https://www.msnbc.com/feeds/latest",
    "website": "https://msnbc.com"
  },
  {
    "id": "sbtnews",
    "name": "SBT News",
    "flag": "🇧🇷",
    "country": "Brazil",
    "city": "São Paulo",
    "lat": -23.4,
    "lon": -46.7,
    "lean": "center",
    "lang": "pt",
    "type": "tv",
    "rssUrl": "https://www.sbtnews.com.br/feed/",
    "website": "https://sbtnews.com.br"
  },
  {
    "id": "recordnews",
    "name": "Record News",
    "flag": "🇧🇷",
    "country": "Brazil",
    "city": "São Paulo",
    "lat": -23.2,
    "lon": -46.9,
    "lean": "right",
    "lang": "pt",
    "type": "tv",
    "rssUrl": "https://recordtv.r7.com/record-news/feed.xml",
    "website": "https://recordtv.r7.com/record-news"
  },
  {
    "id": "rtve",
    "name": "RTVE Noticias",
    "flag": "🇪🇸",
    "country": "Spain",
    "city": "Madrid",
    "lat": 40.4,
    "lon": -3.7,
    "lean": "center",
    "lang": "es",
    "type": "tv",
    "rssUrl": "https://api.rtve.es/api/feeds/noticias.rss",
    "website": "https://rtve.es/noticias"
  },
  {
    "id": "rainews",
    "name": "RAI News 24",
    "flag": "🇮🇹",
    "country": "Italy",
    "city": "Rome",
    "lat": 41.7,
    "lon": 12.3,
    "lean": "center",
    "lang": "it",
    "type": "tv",
    "rssUrl": "https://www.rainews.it/rss/tutti",
    "website": "https://rainews.it"
  },
  {
    "id": "todonoticias",
    "name": "TN - Todo Noticias",
    "flag": "🇦🇷",
    "country": "Argentina",
    "city": "Buenos Aires",
    "lat": -34.6,
    "lon": -58.6,
    "lean": "right",
    "lang": "es",
    "type": "tv",
    "rssUrl": "https://tn.com.ar/rss.xml",
    "website": "https://tn.com.ar"
  },
  {
    "id": "televisa",
    "name": "Televisa Noticias",
    "flag": "🇲🇽",
    "country": "Mexico",
    "city": "Mexico City",
    "lat": 19.4,
    "lon": -99.1,
    "lean": "center",
    "lang": "es",
    "type": "tv",
    "rssUrl": "https://noticieros.televisa.com/feed/",
    "website": "https://noticieros.televisa.com"
  },
  {
    "id": "ndtv",
    "name": "NDTV",
    "flag": "🇮🇳",
    "country": "India",
    "city": "New Delhi",
    "lat": 28,
    "lon": 77,
    "lean": "left",
    "lang": "en",
    "type": "tv",
    "rssUrl": "https://feeds.feedburner.com/ndtvnews-top-stories",
    "website": "https://ndtv.com"
  },
  {
    "id": "wion",
    "name": "WION",
    "flag": "🇮🇳",
    "country": "India",
    "city": "New Delhi",
    "lat": 28.6,
    "lon": 77.8,
    "lean": "center",
    "lang": "en",
    "type": "tv",
    "rssUrl": "https://www.wionews.com/feeds/world/rss.xml",
    "website": "https://wionews.com"
  },
  {
    "id": "arirang",
    "name": "Arirang News",
    "flag": "🇰🇷",
    "country": "South Korea",
    "city": "Seoul",
    "lat": 37.4,
    "lon": 126.8,
    "lean": "center",
    "lang": "en",
    "type": "tv",
    "rssUrl": "https://www.arirang.com/rss/news_list.xml",
    "website": "https://arirang.com"
  },
  {
    "id": "channelstv",
    "name": "Channels TV",
    "flag": "🇳🇬",
    "country": "Nigeria",
    "city": "Lagos",
    "lat": 6.3,
    "lon": 3.6,
    "lean": "center",
    "lang": "en",
    "type": "tv",
    "rssUrl": "https://www.channelstv.com/feed/",
    "website": "https://channelstv.com"
  },
  {
    "id": "enca",
    "name": "eNCA",
    "flag": "🇿🇦",
    "country": "South Africa",
    "city": "Johannesburg",
    "lat": -26,
    "lon": 28.3,
    "lean": "center",
    "lang": "en",
    "type": "tv",
    "rssUrl": "https://www.enca.com/rss",
    "website": "https://enca.com"
  },
  {
    "id": "bloomberg",
    "name": "Bloomberg Markets",
    "flag": "🤑",
    "country": "United States",
    "city": "New York",
    "lat": 40.72,
    "lon": -76.33,
    "lean": "center",
    "lang": "en",
    "type": "market",
    "rssUrl": "https://news.google.com/rss/search?q=source:%22Bloomberg%22&hl=en-US&gl=US&ceid=US:en",
    "website": "https://news.google.com"
  },
  {
    "id": "cnbc",
    "name": "CNBC",
    "flag": "🤑",
    "country": "United States",
    "city": "Englewood Cliffs",
    "lat": 40.8,
    "lon": -73.9,
    "lean": "center",
    "lang": "en",
    "type": "market",
    "rssUrl": "https://search.cnbc.com/rs/search/combinedcms/view.xml?profile=12000009",
    "website": "https://cnbc.com"
  },
  {
    "id": "ft",
    "name": "Financial Times",
    "flag": "🤑",
    "country": "United Kingdom",
    "city": "London",
    "lat": 52.2,
    "lon": -2.28,
    "lean": "center",
    "lang": "en",
    "type": "market",
    "rssUrl": "https://www.ft.com/?format=rss",
    "website": "https://www.ft.com"
  },
  {
    "id": "economist",
    "name": "The Economist",
    "flag": "🤑",
    "country": "United Kingdom",
    "city": "London",
    "lat": 52.5,
    "lon": -1.5,
    "lean": "center",
    "lang": "en",
    "type": "market",
    "rssUrl": "https://www.economist.com/finance-and-economics/rss.xml",
    "website": "https://economist.com"
  },
  {
    "id": "forbes",
    "name": "Forbes Markets",
    "flag": "🤑",
    "country": "United States",
    "city": "Jersey City",
    "lat": 40.7,
    "lon": -74,
    "lean": "center",
    "lang": "en",
    "type": "market",
    "rssUrl": "https://www.forbes.com/markets/feed/",
    "website": "https://forbes.com"
  },
  {
    "id": "investing",
    "name": "Investing.com",
    "flag": "🤑",
    "country": "Cyprus",
    "city": "Nicosia",
    "lat": 34.98,
    "lon": 32.94,
    "lean": "center",
    "lang": "en",
    "type": "market",
    "rssUrl": "https://www.investing.com/rss/news_25.rss",
    "website": "https://www.investing.com"
  },
  {
    "id": "valoreconomico",
    "name": "Valor Econômico",
    "flag": "🤑",
    "country": "Brazil",
    "city": "São Paulo",
    "lat": -23.55,
    "lon": -46.6,
    "lean": "center",
    "lang": "pt",
    "type": "market",
    "rssUrl": "https://valor.globo.com/rss/agronegocios",
    "website": "https://valor.globo.com"
  },
  {
    "id": "infomoney",
    "name": "InfoMoney",
    "flag": "🤑",
    "country": "Brazil",
    "city": "São Paulo",
    "lat": -23.6,
    "lon": -46.7,
    "lean": "center",
    "lang": "pt",
    "type": "market",
    "rssUrl": "https://www.infomoney.com.br/feed/",
    "website": "https://infomoney.com.br"
  },
  {
    "id": "globo",
    "name": "globo",
    "flag": "🌍",
    "country": "User Added",
    "city": "Unknown",
    "lat": -22.44,
    "lon": -44.9,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://g1.globo.com/rss/g1/",
    "website": "https://g1.globo.com"
  },
  {
    "id": "metr-poles",
    "name": "Metrópoles",
    "flag": "🌍",
    "country": "User Added",
    "city": "Brasília",
    "lat": -13.51,
    "lon": -48.5,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.metropoles.com/feed",
    "website": "https://www.metropoles.com"
  },
  {
    "id": "fox-news",
    "name": "Fox News",
    "flag": "🌍",
    "country": "User Added",
    "city": "Unknown",
    "lat": 41.12,
    "lon": -75.32,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://feeds.foxnews.com/foxnews/latest",
    "website": "https://foxnews.com"
  },
  {
    "id": "times-of-india---top-stories",
    "name": "Times of India - top stories",
    "flag": "🌍",
    "country": "User Added",
    "city": "Unknown",
    "lat": 23.01,
    "lon": 75.58,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://timesofindia.indiatimes.com/rssfeedstopstories.cms",
    "website": "https://timesofindia.indiatimes.com"
  },
  {
    "id": "toi---stop-sories",
    "name": "TOI - Stop sories",
    "flag": "🌍",
    "country": "User Added",
    "city": "Unknown",
    "lat": 20.82,
    "lon": 76.74,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://timesofindia.indiatimes.com/rssfeedstopstories.cms",
    "website": "https://timesofindia.indiatimes.com"
  },
  {
    "id": "toi---recent",
    "name": "Times of India - Recent",
    "flag": "🌍",
    "country": "User Added",
    "city": "Mumbai",
    "lat": 20.78,
    "lon": 79.07,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://timesofindia.indiatimes.com/rssfeedmostrecent.cms",
    "website": "https://timesofindia.indiatimes.com"
  },
  {
    "id": "toi---india",
    "name": "Times of India - India",
    "flag": "🌍",
    "country": "User Added",
    "city": "Mumbai",
    "lat": 24.15,
    "lon": 74.39,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://timesofindia.indiatimes.com/rssfeeds/-2128936835.cms",
    "website": "https://timesofindia.indiatimes.com"
  },
  {
    "id": "toi---world",
    "name": "Times of India - World",
    "flag": "🌍",
    "country": "User Added",
    "city": "Unknown",
    "lat": 23.02,
    "lon": 78.06,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://timesofindia.indiatimes.com/rssfeeds/296589292.cms",
    "website": "https://timesofindia.indiatimes.com"
  },
  {
    "id": "toi---business",
    "name": "Times of India - Business",
    "flag": "🌍",
    "country": "User Added",
    "city": "Unknown",
    "lat": 22.37,
    "lon": 75.52,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://timesofindia.indiatimes.com/rssfeeds/1898055.cms",
    "website": "https://timesofindia.indiatimes.com"
  },
  {
    "id": "toi---us",
    "name": "Times of India - US",
    "flag": "🌍",
    "country": "User Added",
    "city": "Unknown",
    "lat": 20.03,
    "lon": 76.53,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://timesofindia.indiatimes.com/rssfeeds_us/72258322.cms",
    "website": "https://timesofindia.indiatimes.com"
  },
  {
    "id": "times-of-india---sports",
    "name": "Times of India - Sports",
    "flag": "🌍",
    "country": "User Added",
    "city": "Mumbai",
    "lat": 22.01,
    "lon": 80.12,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://timesofindia.indiatimes.com/rssfeeds/4719148.cms",
    "website": "https://timesofindia.indiatimes.com"
  },
  {
    "id": "jerusalem-post",
    "name": "Jerusalem Post",
    "flag": "🌍",
    "country": "User Added",
    "city": "Unknown",
    "lat": 30.43,
    "lon": 34.69,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.jpost.com/rss/rssfeedsfrontpage.aspx",
    "website": "https://www.jpost.com"
  },
  {
    "id": "israel-national-news",
    "name": "Israel National News",
    "flag": "🌍",
    "country": "User Added",
    "city": "Unknown",
    "lat": 31.01,
    "lon": 34.81,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.israelnationalnews.com/Rss.aspx",
    "website": "https://www.israelnationalnews.com"
  },
  {
    "id": "defenseone",
    "name": "Defense One",
    "flag": "🇺🇸",
    "country": "United States",
    "city": "Washington, D.C.",
    "lat": 36.77,
    "lon": -78.09,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.defenseone.com/rss/all/",
    "website": "https://www.defenseone.com"
  },
  {
    "id": "defensenews",
    "name": "Defense News",
    "flag": "🇺🇸",
    "country": "United States",
    "city": "Washington, D.C.",
    "lat": 38.91,
    "lon": -77.01,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.defensenews.com/arc/outboundfeeds/rss/",
    "website": "https://www.defensenews.com"
  },
  {
    "id": "politico",
    "name": "Politico",
    "flag": "🇺🇸",
    "country": "United States",
    "city": "Washington, D.C.",
    "lat": 37.16,
    "lon": -80.14,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://rss.politico.com/politics-news.xml",
    "website": "https://rss.politico.com"
  },
  {
    "id": "marketwatch",
    "name": "MarketWatch",
    "flag": "🇺🇸",
    "country": "United States",
    "city": "New York",
    "lat": 40.15,
    "lon": -75.28,
    "lean": "center",
    "lang": "en",
    "rssUrl": "http://feeds.marketwatch.com/marketwatch/topstories",
    "website": "http://feeds.marketwatch.com"
  },
  {
    "id": "daily-sabah",
    "name": "Daily Sabah",
    "flag": "🌍",
    "country": "User Added",
    "city": "Istambul",
    "lat": 39.58,
    "lon": 28.62,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.dailysabah.com/rss/turkiye",
    "website": "https://www.dailysabah.com"
  },
  {
    "id": "cooperativa",
    "name": "Cooperativa",
    "flag": "🇨🇱",
    "country": "Chile",
    "city": "Santiago",
    "lat": -33.45,
    "lon": -70.66,
    "lean": "center",
    "lang": "es",
    "rssUrl": "https://www.cooperativa.cl/noticias/site/tax/port/all/rss_16___1.xml",
    "website": "https://www.cooperativa.cl"
  },
  {
    "id": "latercera",
    "name": "La Tercera",
    "flag": "🇨🇱",
    "country": "Chile",
    "city": "Santiago",
    "lat": -33.5,
    "lon": -70.75,
    "lean": "center-right",
    "lang": "es",
    "rssUrl": "https://www.latercera.com/canal/lo-ultimo/rss/",
    "website": "https://www.latercera.com"
  },
  {
    "id": "cooperativa-pod",
    "name": "Cooperativa Podcast",
    "flag": "🇨🇱",
    "country": "Chile",
    "city": "Santiago",
    "lat": -33.4,
    "lon": -70.55,
    "lean": "center",
    "lang": "es",
    "rssUrl": "https://m.cooperativa.cl/noticias/site/edic/base/rss/_pod_ahora_es_hora.xml",
    "website": "https://m.cooperativa.cl"
  },
  {
    "id": "chinadaily",
    "name": "China Daily",
    "flag": "🇨🇳",
    "country": "China",
    "city": "Beijing",
    "lat": 39.9,
    "lon": 116.4,
    "lean": "right",
    "lang": "en",
    "rssUrl": "http://www.chinadaily.com.cn/rss/china_rss.xml",
    "website": "http://www.chinadaily.com.cn"
  },
  {
    "id": "chinadaily-world",
    "name": "China Daily World",
    "flag": "🇨🇳",
    "country": "China",
    "city": "Beijing",
    "lat": 40.05,
    "lon": 116.55,
    "lean": "right",
    "lang": "en",
    "rssUrl": "http://www.chinadaily.com.cn/rss/world_rss.xml",
    "website": "http://www.chinadaily.com.cn"
  },
  {
    "id": "xinhua",
    "name": "Xinhua News",
    "flag": "🇨🇳",
    "country": "China",
    "city": "Beijing",
    "lat": 39.75,
    "lon": 116.3,
    "lean": "right",
    "lang": "en",
    "rssUrl": "https://www.xinhuanet.com/english/rss/chinarss.xml",
    "website": "https://www.xinhuanet.com"
  },
  {
    "id": "ticotimes",
    "name": "The Tico Times",
    "flag": "🇨🇷",
    "country": "Costa Rica",
    "city": "San José",
    "lat": 9.94,
    "lon": -84.08,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://ticotimes.net/feed",
    "website": "https://ticotimes.net"
  },
  {
    "id": "costaricantimes",
    "name": "The Costa Rican Times",
    "flag": "🇨🇷",
    "country": "Costa Rica",
    "city": "San José",
    "lat": 9.92,
    "lon": -84.09,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.costaricantimes.com/feed",
    "website": "https://www.costaricantimes.com"
  },
  {
    "id": "qcostarica",
    "name": "Q Costa Rica",
    "flag": "🇨🇷",
    "country": "Costa Rica",
    "city": "San José",
    "lat": 9.93,
    "lon": -84.07,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://qcostarica.com/feed",
    "website": "https://qcostarica.com"
  },
  {
    "id": "guatemalacom",
    "name": "Guatemala.com",
    "flag": "🇬🇹",
    "country": "Guatemala",
    "city": "Guatemala City",
    "lat": 14.65,
    "lon": -90.52,
    "lean": "center",
    "lang": "es",
    "rssUrl": "https://www.guatemala.com/feed",
    "website": "https://www.guatemala.com"
  },
  {
    "id": "prensalibre",
    "name": "Prensa Libre",
    "flag": "🇬🇹",
    "country": "Guatemala",
    "city": "Guatemala City",
    "lat": 14.62,
    "lon": -90.51,
    "lean": "center",
    "lang": "es",
    "rssUrl": "https://www.prensalibre.com/feed",
    "website": "https://www.prensalibre.com"
  },
  {
    "id": "publinews-gt",
    "name": "Publinews Guatemala",
    "flag": "🇬🇹",
    "country": "Guatemala",
    "city": "Guatemala City",
    "lat": 14.63,
    "lon": -90.5,
    "lean": "center",
    "lang": "es",
    "rssUrl": "https://www.publinews.gt/feed",
    "website": "https://www.publinews.gt"
  },
  {
    "id": "elfaro",
    "name": "El Faro",
    "flag": "🇸🇻",
    "country": "El Salvador",
    "city": "San Salvador",
    "lat": 13.69,
    "lon": -89.21,
    "lean": "left",
    "lang": "es",
    "rssUrl": "https://elfaro.net/es/rss.xml",
    "website": "https://elfaro.net"
  },
  {
    "id": "laprensa-ni",
    "name": "La Prensa Nicaragua",
    "flag": "🇳🇮",
    "country": "Nicaragua",
    "city": "Managua",
    "lat": 12.13,
    "lon": -86.23,
    "lean": "center",
    "lang": "es",
    "rssUrl": "https://www.laprensa.com.ni/feed",
    "website": "https://www.laprensa.com.ni"
  },
  {
    "id": "proceso-hn",
    "name": "Proceso Digital",
    "flag": "🇭🇳",
    "country": "Honduras",
    "city": "Tegucigalpa",
    "lat": 14.07,
    "lon": -87.19,
    "lean": "center",
    "lang": "es",
    "rssUrl": "https://proceso.hn/feed",
    "website": "https://proceso.hn"
  },
  {
    "id": "latinvex",
    "name": "Latinvex",
    "flag": "🌎",
    "country": "Regional",
    "city": "Panama City",
    "lat": 9,
    "lon": -79.5,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://latinvex.com/feed",
    "website": "https://latinvex.com"
  },
  {
    "id": "perureports",
    "name": "Peru Reports",
    "flag": "🇵🇪",
    "country": "Peru",
    "city": "Lima",
    "lat": -9.73,
    "lon": -74.68,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://perureports.com/feed/",
    "website": "https://perureports.com"
  },
  {
    "id": "caretas",
    "name": "Caretas",
    "flag": "🇵🇪",
    "country": "Peru",
    "city": "Lima",
    "lat": -12.03,
    "lon": -77.02,
    "lean": "center",
    "lang": "es",
    "rssUrl": "https://caretas.pe/feed/",
    "website": "https://caretas.pe"
  },
  {
    "id": "generaccion",
    "name": "Gener Acción",
    "flag": "🇵🇪",
    "country": "Peru",
    "city": "Lima",
    "lat": -12.05,
    "lon": -77.01,
    "lean": "center",
    "lang": "es",
    "rssUrl": "https://generaccion.com/noticia/rss",
    "website": "https://generaccion.com"
  },
  {
    "id": "peruvian-times",
    "name": "Peruvian Times",
    "flag": "🇵🇪",
    "country": "Peru",
    "city": "Lima",
    "lat": -12.07,
    "lon": -77.06,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://feeds.feedburner.com/PeruvianTimes",
    "website": "https://peruviantimes.com"
  },
  {
    "id": "caracaschronicles",
    "name": "Caracas Chronicles",
    "flag": "🇻🇪",
    "country": "Venezuela",
    "city": "Caracas",
    "lat": 8.54,
    "lon": -66.31,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://caracaschronicles.com/feed/",
    "website": "https://caracaschronicles.com"
  },
  {
    "id": "eldiario-ve",
    "name": "El Diario",
    "flag": "🇻🇪",
    "country": "Venezuela",
    "city": "Caracas",
    "lat": 8.73,
    "lon": -68.47,
    "lean": "center",
    "lang": "es",
    "rssUrl": "https://eldiario.com/feed/",
    "website": "https://eldiario.com"
  },
  {
    "id": "ultimasnoticias-ve",
    "name": "Últimas Noticias",
    "flag": "🇻🇪",
    "country": "Venezuela",
    "city": "Caracas",
    "lat": 10.47,
    "lon": -66.9,
    "lean": "center",
    "lang": "es",
    "rssUrl": "https://ultimasnoticias.com.ve/feed/",
    "website": "https://ultimasnoticias.com.ve"
  },
  {
    "id": "elnacional-ve",
    "name": "El Nacional",
    "flag": "🇻🇪",
    "country": "Venezuela",
    "city": "Caracas",
    "lat": 10.48,
    "lon": -66.91,
    "lean": "center",
    "lang": "es",
    "rssUrl": "https://elnacional.com/feed/",
    "website": "https://elnacional.com"
  },
  {
    "id": "elpepazo-ve",
    "name": "El Pepazo",
    "flag": "🇻🇪",
    "country": "Venezuela",
    "city": "Caracas",
    "lat": 10.5,
    "lon": -66.87,
    "lean": "center",
    "lang": "es",
    "rssUrl": "https://elpepazo.com/rss-feeds",
    "website": "https://elpepazo.com"
  },
  {
    "id": "latinvex-bo",
    "name": "Latinvex Bolivia",
    "flag": "🇧🇴",
    "country": "Bolivia",
    "city": "La Paz",
    "lat": -16.5,
    "lon": -68.15,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.latinvex.com/feed/?country=bolivia",
    "website": "https://latinvex.com"
  },
  {
    "id": "lostiempos",
    "name": "Los Tiempos",
    "flag": "🇧🇴",
    "country": "Bolivia",
    "city": "Cochabamba",
    "lat": -17.39,
    "lon": -66.15,
    "lean": "center",
    "lang": "es",
    "rssUrl": "https://www.lostiempos.com/rss",
    "website": "https://lostiempos.com"
  },
  {
    "id": "eldeber",
    "name": "El Deber",
    "flag": "🇧🇴",
    "country": "Bolivia",
    "city": "Santa Cruz",
    "lat": -17.78,
    "lon": -63.18,
    "lean": "center",
    "lang": "es",
    "rssUrl": "https://eldeber.com.bo/rss",
    "website": "https://eldeber.com.bo"
  },
  {
    "id": "opinion-bo",
    "name": "Opinión",
    "flag": "🇧🇴",
    "country": "Bolivia",
    "city": "Cochabamba",
    "lat": -17.41,
    "lon": -66.17,
    "lean": "center",
    "lang": "es",
    "rssUrl": "https://www.opinion.com.bo/rss",
    "website": "https://opinion.com.bo"
  },
  {
    "id": "tass",
    "name": "TASS",
    "flag": "🇷🇺",
    "country": "Russia",
    "city": "Moscow",
    "lat": 55.75,
    "lon": 37.62,
    "lean": "right",
    "lang": "en",
    "rssUrl": "https://tass.com/rss/v2.xml",
    "website": "https://tass.com"
  },
  {
    "id": "rt",
    "name": "RT",
    "flag": "🇷🇺",
    "country": "Russia",
    "city": "Moscow",
    "lat": 55.77,
    "lon": 37.65,
    "lean": "right",
    "lang": "en",
    "rssUrl": "https://www.rt.com/rss/",
    "website": "https://www.rt.com"
  },
  {
    "id": "ria-ru",
    "name": "RIA Novosti",
    "flag": "🇷🇺",
    "country": "Russia",
    "city": "Moscow",
    "lat": 55.72,
    "lon": 37.6,
    "lean": "right",
    "lang": "ru",
    "rssUrl": "https://ria.ru/export/rss2/index.xml",
    "website": "https://ria.ru"
  },
  {
    "id": "meduza-en",
    "name": "Meduza (English)",
    "flag": "🇷🇺",
    "country": "Russia",
    "city": "Moscow",
    "lat": 55.74,
    "lon": 37.58,
    "lean": "left",
    "lang": "en",
    "rssUrl": "https://meduza.io/rss/en/all",
    "website": "https://meduza.io"
  },
  {
    "id": "moscowtimes",
    "name": "The Moscow Times",
    "flag": "🇷🇺",
    "country": "Russia",
    "city": "Moscow",
    "lat": 55.76,
    "lon": 37.64,
    "lean": "left",
    "lang": "en",
    "rssUrl": "https://www.themoscowtimes.com/rss/news",
    "website": "https://www.themoscowtimes.com"
  },
  {
    "id": "mediazona",
    "name": "Mediazona",
    "flag": "🇷🇺",
    "country": "Russia",
    "city": "Moscow",
    "lat": 55.71,
    "lon": 37.66,
    "lean": "left",
    "lang": "ru",
    "rssUrl": "https://zona.media/rss.xml",
    "website": "https://zona.media"
  },
  {
    "id": "novayagazeta-eu",
    "name": "Novaya Gazeta Europe",
    "flag": "🇷🇺",
    "country": "Russia",
    "city": "Moscow",
    "lat": 55.79,
    "lon": 37.59,
    "lean": "left",
    "lang": "en",
    "rssUrl": "https://novayagazeta.eu/rss/all",
    "website": "https://novayagazeta.eu"
  },
  {
    "id": "africanews",
    "name": "Africanews",
    "flag": "🌍",
    "country": "Pan-African",
    "city": "Addis Ababa",
    "lat": 9.02,
    "lon": 38.74,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.africanews.com/feed/",
    "website": "https://www.africanews.com"
  },
  {
    "id": "theafricareport",
    "name": "The Africa Report",
    "flag": "🌍",
    "country": "Pan-African",
    "city": "Addis Ababa",
    "lat": 8.98,
    "lon": 38.76,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.theafricareport.com/feed/",
    "website": "https://www.theafricareport.com"
  },
  {
    "id": "jeuneafrique",
    "name": "Jeune Afrique",
    "flag": "🌍",
    "country": "Pan-African",
    "city": "Addis Ababa",
    "lat": 9.01,
    "lon": 38.72,
    "lean": "center",
    "lang": "fr",
    "rssUrl": "https://www.jeuneafrique.com/feed/",
    "website": "https://www.jeuneafrique.com"
  },
  {
    "id": "news24",
    "name": "News24",
    "flag": "🇿🇦",
    "country": "South Africa",
    "city": "Cape Town",
    "lat": -33.92,
    "lon": 18.42,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.news24.com/news24/rss",
    "website": "https://www.news24.com"
  },
  {
    "id": "dailymaverick",
    "name": "Daily Maverick",
    "flag": "🇿🇦",
    "country": "South Africa",
    "city": "Johannesburg",
    "lat": -26.21,
    "lon": 28.03,
    "lean": "left",
    "lang": "en",
    "rssUrl": "https://www.dailymaverick.co.za/feed/",
    "website": "https://www.dailymaverick.co.za"
  },
  {
    "id": "premiumtimesng",
    "name": "Premium Times Nigeria",
    "flag": "🇳🇬",
    "country": "Nigeria",
    "city": "Abuja",
    "lat": 9.07,
    "lon": 7.39,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.premiumtimesng.com/feed",
    "website": "https://www.premiumtimesng.com"
  },
  {
    "id": "guardian-ng",
    "name": "Guardian Nigeria",
    "flag": "🇳🇬",
    "country": "Nigeria",
    "city": "Lagos",
    "lat": 6.52,
    "lon": 3.37,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://guardian.ng/feed/",
    "website": "https://guardian.ng"
  },
  {
    "id": "vanguard-ngr",
    "name": "Vanguard News",
    "flag": "🇳🇬",
    "country": "Nigeria",
    "city": "Lagos",
    "lat": 6.45,
    "lon": 3.42,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.vanguardngr.com/feed/",
    "website": "https://www.vanguardngr.com"
  },
  {
    "id": "standardmedia",
    "name": "Standard Media Kenya",
    "flag": "🇰🇪",
    "country": "Kenya",
    "city": "Nairobi",
    "lat": -1.28,
    "lon": 36.82,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.standardmedia.co.ke/rss",
    "website": "https://www.standardmedia.co.ke"
  },
  {
    "id": "ahram-online",
    "name": "Ahram Online",
    "flag": "🇪🇬",
    "country": "Egypt",
    "city": "Cairo",
    "lat": 30.04,
    "lon": 31.23,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://english.ahram.org.eg/rss/rss.aspx",
    "website": "https://english.ahram.org.eg"
  },
  {
    "id": "egyptindependent",
    "name": "Egypt Independent",
    "flag": "🇪🇬",
    "country": "Egypt",
    "city": "Cairo",
    "lat": 30.06,
    "lon": 31.21,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.egyptindependent.com/feed/",
    "website": "https://www.egyptindependent.com"
  },
  {
    "id": "lajornada",
    "name": "La Jornada",
    "flag": "🇲🇽",
    "country": "Mexico",
    "city": "Mexico City",
    "lat": 19.42,
    "lon": -99.14,
    "lean": "left",
    "lang": "es",
    "rssUrl": "https://www.jornada.com.mx/rss",
    "website": "https://lajornada.com.mx"
  },
  {
    "id": "animalpolitico",
    "name": "Animal Político",
    "flag": "🇲🇽",
    "country": "Mexico",
    "city": "Mexico City",
    "lat": 19.45,
    "lon": -99.12,
    "lean": "left",
    "lang": "es",
    "rssUrl": "https://animalpolitico.com/feed/",
    "website": "https://animalpolitico.com"
  },
  {
    "id": "excelsior",
    "name": "Excélsior",
    "flag": "🇲🇽",
    "country": "Mexico",
    "city": "Mexico City",
    "lat": 19.41,
    "lon": -99.15,
    "lean": "right",
    "lang": "es",
    "rssUrl": "https://www.excelsior.com.mx/rss.xml",
    "website": "https://excelsior.com.mx"
  },
  {
    "id": "cbc",
    "name": "CBC News",
    "flag": "🇨🇦",
    "country": "Canada",
    "city": "Ottawa",
    "lat": 45.42,
    "lon": -75.7,
    "lean": "center-left",
    "lang": "en",
    "rssUrl": "https://www.cbc.ca/cmlink/rss-topstories",
    "website": "https://www.cbc.ca"
  },
  {
    "id": "globalnews-ca",
    "name": "Global News",
    "flag": "🇨🇦",
    "country": "Canada",
    "city": "Toronto",
    "lat": 43.65,
    "lon": -79.38,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://globalnews.ca/feed/",
    "website": "https://globalnews.ca"
  },
  {
    "id": "ctvnews-ca",
    "name": "CTV News",
    "flag": "🇨🇦",
    "country": "Canada",
    "city": "Toronto",
    "lat": 43.66,
    "lon": -79.37,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.ctvnews.ca/rss/ctvnews-ca-top-stories-public-rss-1.822009",
    "website": "https://www.ctvnews.ca"
  },
  {
    "id": "nationalpost-ca",
    "name": "National Post",
    "flag": "🇨🇦",
    "country": "Canada",
    "city": "Toronto",
    "lat": 43.64,
    "lon": -79.39,
    "lean": "right",
    "lang": "en",
    "rssUrl": "https://nationalpost.com/feed/",
    "website": "https://nationalpost.com"
  },
  {
    "id": "globemail-ca",
    "name": "The Globe and Mail",
    "flag": "🇨🇦",
    "country": "Canada",
    "city": "Toronto",
    "lat": 43.67,
    "lon": -79.4,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.theglobeandmail.com/arc/outboundfeeds/rss/",
    "website": "https://theglobeandmail.com"
  },
  {
    "id": "cubadebate",
    "name": "Cubadebate",
    "flag": "🇨🇺",
    "country": "Cuba",
    "city": "Havana",
    "lat": 23.11,
    "lon": -82.36,
    "lean": "right",
    "lang": "es",
    "rssUrl": "http://www.cubadebate.cu/feed/",
    "website": "http://www.cubadebate.cu"
  },
  {
    "id": "granma",
    "name": "Granma",
    "flag": "🇨🇺",
    "country": "Cuba",
    "city": "Havana",
    "lat": 23.13,
    "lon": -82.38,
    "lean": "right",
    "lang": "es",
    "rssUrl": "http://www.granma.cu/rss",
    "website": "http://www.granma.cu"
  },
  {
    "id": "oncubanews",
    "name": "OnCubaNews",
    "flag": "🇨🇺",
    "country": "Cuba",
    "city": "Havana",
    "lat": 23.12,
    "lon": -82.37,
    "lean": "left",
    "lang": "es",
    "rssUrl": "https://oncubanews.com/feed/",
    "website": "https://oncubanews.com"
  },
  {
    "id": "periodicocubano",
    "name": "Periódico Cubano",
    "flag": "🇨🇺",
    "country": "Cuba",
    "city": "Havana",
    "lat": 23.1,
    "lon": -82.35,
    "lean": "left",
    "lang": "es",
    "rssUrl": "https://www.periodicocubano.com/feed/",
    "website": "https://periodicocubano.com"
  },
  {
    "id": "sermitsiaq",
    "name": "Sermitsiaq",
    "flag": "🇬🇱",
    "country": "Greenland",
    "city": "Nuuk",
    "lat": 64.18,
    "lon": -51.72,
    "lean": "center",
    "lang": "da",
    "rssUrl": "https://sermitsiaq.ag/rss",
    "website": "https://sermitsiaq.ag"
  },
  {
    "id": "knr-gl",
    "name": "KNR",
    "flag": "🇬🇱",
    "country": "Greenland",
    "city": "Nuuk",
    "lat": 64.19,
    "lon": -51.73,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://knr.gl/en/rss.xml",
    "website": "https://knr.gl"
  },
  {
    "id": "polskie_radio",
    "name": "Polskie Radio",
    "flag": "🇵🇱",
    "country": "Poland",
    "city": "Warsaw",
    "lat": 52.23,
    "lon": 21.01,
    "lean": "right",
    "lang": "pl",
    "rssUrl": "https://www.polskieradio.pl/rss",
    "website": "https://www.polskieradio.pl"
  },
  {
    "id": "tvp_info",
    "name": "TVP Info",
    "flag": "🇵🇱",
    "country": "Poland",
    "city": "Warsaw",
    "lat": 52.24,
    "lon": 21.02,
    "lean": "right",
    "lang": "pl",
    "rssUrl": "https://www.tvp.info/rss",
    "website": "https://www.tvp.info"
  },
  {
    "id": "notes_poland",
    "name": "Notes from Poland",
    "flag": "🇵🇱",
    "country": "Poland",
    "city": "Krakow",
    "lat": 50.06,
    "lon": 19.94,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://notesfrompoland.com/feed/",
    "website": "https://notesfrompoland.com"
  },
  {
    "id": "first_news",
    "name": "The First News",
    "flag": "🇵🇱",
    "country": "Poland",
    "city": "Warsaw",
    "lat": 52.25,
    "lon": 21.03,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.thefirstnews.com/feed",
    "website": "https://www.thefirstnews.com"
  },
  {
    "id": "rp_pl",
    "name": "Rzeczpospolita",
    "flag": "🇵🇱",
    "country": "Poland",
    "city": "Warsaw",
    "lat": 52.22,
    "lon": 21,
    "lean": "center",
    "lang": "pl",
    "rssUrl": "https://www.rp.pl/rss",
    "website": "https://www.rp.pl"
  },
  {
    "id": "der_standard",
    "name": "Der Standard",
    "flag": "🇦🇹",
    "country": "Austria",
    "city": "Vienna",
    "lat": 48.2,
    "lon": 16.37,
    "lean": "left",
    "lang": "de",
    "rssUrl": "https://www.derstandard.at/rss",
    "website": "https://www.derstandard.at"
  },
  {
    "id": "die_presse",
    "name": "Die Presse",
    "flag": "🇦🇹",
    "country": "Austria",
    "city": "Vienna",
    "lat": 48.21,
    "lon": 16.38,
    "lean": "right",
    "lang": "de",
    "rssUrl": "https://www.diepresse.com/rss",
    "website": "https://www.diepresse.com"
  },
  {
    "id": "orf_at",
    "name": "ORF.at",
    "flag": "🇦🇹",
    "country": "Austria",
    "city": "Vienna",
    "lat": 48.19,
    "lon": 16.36,
    "lean": "center",
    "lang": "de",
    "rssUrl": "https://orf.at/stories/rss",
    "website": "https://orf.at"
  },
  {
    "id": "the_local_at",
    "name": "The Local Austria",
    "flag": "🇦🇹",
    "country": "Austria",
    "city": "Vienna",
    "lat": 48.18,
    "lon": 16.35,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.thelocal.at/feeds/rss",
    "website": "https://www.thelocal.at"
  },
  {
    "id": "telex_hu",
    "name": "Telex",
    "flag": "🇭🇺",
    "country": "Hungary",
    "city": "Budapest",
    "lat": 47.49,
    "lon": 19.04,
    "lean": "center",
    "lang": "hu",
    "rssUrl": "https://telex.hu/rss",
    "website": "https://telex.hu"
  },
  {
    "id": "four_four_four_hu",
    "name": "444.hu",
    "flag": "🇭🇺",
    "country": "Hungary",
    "city": "Budapest",
    "lat": 47.5,
    "lon": 19.05,
    "lean": "left",
    "lang": "hu",
    "rssUrl": "https://444.hu/feed",
    "website": "https://444.hu"
  },
  {
    "id": "daily_news_hungary",
    "name": "Daily News Hungary",
    "flag": "🇭🇺",
    "country": "Hungary",
    "city": "Budapest",
    "lat": 47.48,
    "lon": 19.03,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://dailynewshungary.com/feed/",
    "website": "https://dailynewshungary.com"
  },
  {
    "id": "hungary_today",
    "name": "Hungary Today",
    "flag": "🇭🇺",
    "country": "Hungary",
    "city": "Budapest",
    "lat": 47.47,
    "lon": 19.02,
    "lean": "right",
    "lang": "en",
    "rssUrl": "https://hungarytoday.hu/feed/",
    "website": "https://hungarytoday.hu"
  },
  {
    "id": "bbc_europe",
    "name": "BBC News Europe",
    "flag": "🌐",
    "country": "United Kingdom",
    "city": "London",
    "lat": 51.52,
    "lon": -0.11,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://feeds.bbci.co.uk/news/world/europe/rss.xml",
    "website": "https://bbc.co.uk/news"
  },
  {
    "id": "euronews_europe",
    "name": "Euronews Europe",
    "flag": "🌐",
    "country": "France",
    "city": "Lyon",
    "lat": 45.74,
    "lon": 4.81,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.euronews.com/rss?level=theme&name=europe",
    "website": "https://euronews.com"
  },
  {
    "id": "morocco_world_news",
    "name": "Morocco World News",
    "flag": "🇲🇦",
    "country": "Morocco",
    "city": "Rabat",
    "lat": 34.02,
    "lon": -6.83,
    "lean": "right",
    "lang": "en",
    "rssUrl": "https://www.moroccoworldnews.com/feed",
    "website": "https://www.moroccoworldnews.com"
  },
  {
    "id": "hespress",
    "name": "Hespress",
    "flag": "🇲🇦",
    "country": "Morocco",
    "city": "Rabat",
    "lat": 34.01,
    "lon": -6.84,
    "lean": "right",
    "lang": "ar",
    "rssUrl": "https://www.hespress.com/feed",
    "website": "https://www.hespress.com"
  },
  {
    "id": "le_matin_ma",
    "name": "Le Matin",
    "flag": "🇲🇦",
    "country": "Morocco",
    "city": "Casablanca",
    "lat": 33.57,
    "lon": -7.58,
    "lean": "right",
    "lang": "fr",
    "rssUrl": "https://lematin.ma/rss",
    "website": "https://lematin.ma"
  },
  {
    "id": "yabiladi",
    "name": "Yabiladi",
    "flag": "🇲🇦",
    "country": "Morocco",
    "city": "Casablanca",
    "lat": 33.58,
    "lon": -7.57,
    "lean": "center",
    "lang": "fr",
    "rssUrl": "https://www.yabiladi.com/rss/",
    "website": "https://www.yabiladi.com"
  },
  {
    "id": "aps_dz",
    "name": "Algeria Press Service",
    "flag": "🇩🇿",
    "country": "Algeria",
    "city": "Algiers",
    "lat": 36.75,
    "lon": 3.06,
    "lean": "right",
    "lang": "en",
    "rssUrl": "https://www.aps.dz/en/rss",
    "website": "https://www.aps.dz"
  },
  {
    "id": "el_watan_dz",
    "name": "El Watan",
    "flag": "🇩🇿",
    "country": "Algeria",
    "city": "Algiers",
    "lat": 36.74,
    "lon": 3.05,
    "lean": "center",
    "lang": "fr",
    "rssUrl": "https://www.elwatan.com/feed",
    "website": "https://www.elwatan.com"
  },
  {
    "id": "tsa_algerie",
    "name": "TSA Algérie",
    "flag": "🇩🇿",
    "country": "Algeria",
    "city": "Algiers",
    "lat": 36.73,
    "lon": 3.07,
    "lean": "center",
    "lang": "fr",
    "rssUrl": "https://www.tsa-algerie.com/feed/",
    "website": "https://www.tsa-algerie.com"
  },
  {
    "id": "tap_info_tn",
    "name": "TAP (Tunis Afrique Presse)",
    "flag": "🇹🇳",
    "country": "Tunisia",
    "city": "Tunis",
    "lat": 36.8,
    "lon": 10.18,
    "lean": "right",
    "lang": "en",
    "rssUrl": "https://www.tap.info.tn/en/rss",
    "website": "https://www.tap.info.tn"
  },
  {
    "id": "mosaique_fm",
    "name": "Mosaïque FM",
    "flag": "🇹🇳",
    "country": "Tunisia",
    "city": "Tunis",
    "lat": 36.81,
    "lon": 10.19,
    "lean": "center",
    "lang": "fr",
    "rssUrl": "https://www.mosaiquefm.net/en/rss",
    "website": "https://www.mosaiquefm.net"
  },
  {
    "id": "business_news_tn",
    "name": "Business News",
    "flag": "🇹🇳",
    "country": "Tunisia",
    "city": "Tunis",
    "lat": 36.79,
    "lon": 10.17,
    "lean": "center",
    "lang": "fr",
    "rssUrl": "https://www.businessnews.com.tn/rss",
    "website": "https://www.businessnews.com.tn"
  },
  {
    "id": "libya_herald",
    "name": "Libya Herald",
    "flag": "🇱🇾",
    "country": "Libya",
    "city": "Tripoli",
    "lat": 32.88,
    "lon": 13.18,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.libyaherald.com/feed/",
    "website": "https://www.libyaherald.com"
  },
  {
    "id": "libya_observer",
    "name": "Libya Observer",
    "flag": "🇱🇾",
    "country": "Libya",
    "city": "Tripoli",
    "lat": 32.89,
    "lon": 13.19,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.libyaobserver.ly/rss.xml",
    "website": "https://www.libyaobserver.ly"
  },
  {
    "id": "mehrnews",
    "name": "Mehr News Agency",
    "flag": "🇮🇷",
    "country": "Iran",
    "city": "Tehran",
    "lat": 35.7,
    "lon": 51.4,
    "lean": "right",
    "lang": "en",
    "rssUrl": "https://en.mehrnews.com/rss",
    "website": "https://en.mehrnews.com"
  },
  {
    "id": "tasnimnews",
    "name": "Tasnim News Agency",
    "flag": "🇮🇷",
    "country": "Iran",
    "city": "Tehran",
    "lat": 35.75,
    "lon": 51.45,
    "lean": "right",
    "lang": "en",
    "rssUrl": "https://www.tasnimnews.com/en/rss/feed/0/0/1",
    "website": "https://www.tasnimnews.com"
  },
  {
    "id": "tehrantimes",
    "name": "Tehran Times",
    "flag": "🇮🇷",
    "country": "Iran",
    "city": "Tehran",
    "lat": 35.65,
    "lon": 51.35,
    "lean": "right",
    "lang": "en",
    "rssUrl": "https://www.tehrantimes.com/rss",
    "website": "https://www.tehrantimes.com"
  },
  {
    "id": "ifpnews",
    "name": "Iran Front Page",
    "flag": "🇮🇷",
    "country": "Iran",
    "city": "Tehran",
    "lat": 35.8,
    "lon": 51.5,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://ifpnews.com/feed/",
    "website": "https://ifpnews.com"
  },
  {
    "id": "irannewsdaily",
    "name": "Iran News Daily",
    "flag": "🇮🇷",
    "country": "Iran",
    "city": "Tehran",
    "lat": 35.55,
    "lon": 51.25,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.irannewsdaily.com/feed/",
    "website": "https://www.irannewsdaily.com"
  },
  {
    "id": "iranherald",
    "name": "Iran Herald",
    "flag": "🇮🇷",
    "country": "Iran",
    "city": "Tehran",
    "lat": 35.9,
    "lon": 51.55,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://feeds.iranherald.com/rss",
    "website": "https://iranherald.com"
  },
  {
    "id": "radiookapi",
    "name": "Radio Okapi (ONU)",
    "flag": "🇨🇩",
    "country": "DR Congo",
    "city": "Kinshasa",
    "lat": -4.44,
    "lon": 15.26,
    "lean": "center",
    "lang": "fr",
    "rssUrl": "https://www.radiookapi.net/rss.xml",
    "website": "https://www.radiookapi.net"
  },
  {
    "id": "actualitecd",
    "name": "Actualité.cd",
    "flag": "🇨🇩",
    "country": "DR Congo",
    "city": "Kinshasa",
    "lat": -4.51,
    "lon": 15.3,
    "lean": "left",
    "lang": "fr",
    "rssUrl": "https://actualite.cd/rss.xml",
    "website": "https://actualite.cd"
  },
  {
    "id": "politicocd",
    "name": "Politico.cd",
    "flag": "🇨🇩",
    "country": "DR Congo",
    "city": "Kinshasa",
    "lat": -4.4,
    "lon": 15.4,
    "lean": "right",
    "lang": "fr",
    "rssUrl": "https://www.politico.cd/feed/",
    "website": "https://www.politico.cd"
  },
  {
    "id": "mediacongo",
    "name": "MediaCongo",
    "flag": "🇨🇩",
    "country": "DR Congo",
    "city": "Kinshasa",
    "lat": -4.3,
    "lon": 15.1,
    "lean": "center",
    "lang": "fr",
    "rssUrl": "https://www.mediacongo.net/rss",
    "website": "https://www.mediacongo.net"
  },
  {
    "id": "angop",
    "name": "ANGOP Agency",
    "flag": "🇦🇴",
    "country": "Angola",
    "city": "Luanda",
    "lat": -8.84,
    "lon": 13.29,
    "lean": "right",
    "lang": "pt",
    "rssUrl": "https://www.angop.ao/rss/",
    "website": "https://www.angop.ao"
  },
  {
    "id": "jornaldeangola",
    "name": "Jornal de Angola",
    "flag": "🇦🇴",
    "country": "Angola",
    "city": "Luanda",
    "lat": -8.9,
    "lon": 13.35,
    "lean": "right",
    "lang": "pt",
    "rssUrl": "https://www.jornaldeangola.ao/rss",
    "website": "https://www.jornaldeangola.ao"
  },
  {
    "id": "clubek",
    "name": "Club-K Angola",
    "flag": "🇦🇴",
    "country": "Angola",
    "city": "Luanda",
    "lat": -8.7,
    "lon": 13.15,
    "lean": "left",
    "lang": "pt",
    "rssUrl": "https://www.clube-k.net/index.php?format=feed&type=rss",
    "website": "https://www.clube-k.net"
  },
  {
    "id": "novojornal",
    "name": "Novo Jornal",
    "flag": "🇦🇴",
    "country": "Angola",
    "city": "Luanda",
    "lat": -9,
    "lon": 13.1,
    "lean": "left",
    "lang": "pt",
    "rssUrl": "https://www.novojornal.co.ao/rss",
    "website": "https://www.novojornal.co.ao"
  },
  {
    "id": "thecitizen",
    "name": "The Citizen TZ",
    "flag": "🇹🇿",
    "country": "Tanzania",
    "city": "Dar es Salaam",
    "lat": -6.79,
    "lon": 39.21,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.thecitizen.co.tz/rss",
    "website": "https://www.thecitizen.co.tz"
  },
  {
    "id": "theeastafrican",
    "name": "The East African",
    "flag": "🌍",
    "country": "Kenya/Tanzania",
    "city": "Regional",
    "lat": -1.29,
    "lon": 36.82,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.theeastafrican.co.ke/rss",
    "website": "https://www.theeastafrican.co.ke"
  },
  {
    "id": "dailynewstz",
    "name": "Daily News TZ",
    "flag": "🇹🇿",
    "country": "Tanzania",
    "city": "Dar es Salaam",
    "lat": -6.7,
    "lon": 39.3,
    "lean": "right",
    "lang": "en",
    "rssUrl": "https://dailynews.co.tz/rss",
    "website": "https://dailynews.co.tz"
  },
  {
    "id": "allafrica",
    "name": "AllAfrica.com",
    "flag": "🌐",
    "country": "Africa",
    "city": "Regional Hub",
    "lat": 9.01,
    "lon": 38.74,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://allafrica.com/tools/headlines/rdf/latest/headlines.rdf",
    "website": "https://allafrica.com"
  },
  {
    "id": "africanews",
    "name": "Africanews",
    "flag": "🌐",
    "country": "Africa",
    "city": "Lyon/Regional",
    "lat": -4.26,
    "lon": 15.28,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.africanews.com/feed/",
    "website": "https://www.africanews.com"
  },
  {
    "id": "bbcafrica",
    "name": "BBC News Africa",
    "flag": "🇬🇧",
    "country": "UK/Africa Focus",
    "city": "London",
    "lat": 51.5,
    "lon": -0.12,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://feeds.bbci.co.uk/news/world/africa/rss.xml",
    "website": "https://bbc.com/news/world/africa"
  },
  {
    "id": "animalpolitico",
    "name": "Animal Político",
    "flag": "🇲🇽",
    "country": "Mexico",
    "city": "Mexico City",
    "lat": 19.45,
    "lon": -99.15,
    "lean": "left",
    "lang": "es",
    "rssUrl": "https://animalpolitico.com/feed/",
    "website": "https://animalpolitico.com"
  },
  {
    "id": "lajornadamx",
    "name": "La Jornada",
    "flag": "🇲🇽",
    "country": "Mexico",
    "city": "Mexico City",
    "lat": 19.4,
    "lon": -99.1,
    "lean": "left",
    "lang": "es",
    "rssUrl": "https://www.jornada.com.mx/rss",
    "website": "https://www.jornada.com.mx"
  },
  {
    "id": "proceso",
    "name": "Proceso",
    "flag": "🇲🇽",
    "country": "Mexico",
    "city": "Mexico City",
    "lat": 19.42,
    "lon": -99.12,
    "lean": "center",
    "lang": "es",
    "rssUrl": "https://www.proceso.com.mx/rss",
    "website": "https://www.proceso.com.mx"
  },
  {
    "id": "g1globo",
    "name": "G1 Globo",
    "flag": "🇧🇷",
    "country": "Brazil",
    "city": "Rio de Janeiro",
    "lat": -22.9,
    "lon": -43.17,
    "lean": "center",
    "lang": "pt",
    "rssUrl": "https://g1.globo.com/rss/g1/",
    "website": "https://g1.globo.com"
  },
  {
    "id": "folhauol",
    "name": "Folha de S.Paulo",
    "flag": "🇧🇷",
    "country": "Brazil",
    "city": "São Paulo",
    "lat": -23.55,
    "lon": -46.63,
    "lean": "center",
    "lang": "pt",
    "rssUrl": "https://www1.folha.uol.com.br/rss091.xml",
    "website": "https://www.folha.uol.com.br"
  },
  {
    "id": "estadao",
    "name": "Estadão",
    "flag": "🇧🇷",
    "country": "Brazil",
    "city": "São Paulo",
    "lat": -23.6,
    "lon": -46.7,
    "lean": "right",
    "lang": "pt",
    "rssUrl": "https://www.estadao.com.br/rss/ultimas.xml",
    "website": "https://www.estadao.com.br"
  },
  {
    "id": "cnnbrasil",
    "name": "CNN Brasil",
    "flag": "🇧🇷",
    "country": "Brazil",
    "city": "São Paulo",
    "lat": -23.45,
    "lon": -46.55,
    "lean": "center",
    "lang": "pt",
    "rssUrl": "https://www.cnnbrasil.com.br/rss/",
    "website": "https://www.cnnbrasil.com.br"
  },
  {
    "id": "uolnoticias",
    "name": "UOL Notícias",
    "flag": "🇧🇷",
    "country": "Brazil",
    "city": "São Paulo",
    "lat": -23.5,
    "lon": -46.5,
    "lean": "center",
    "lang": "pt",
    "rssUrl": "https://noticias.uol.com.br/ultimas-noticias/rss091.xml",
    "website": "https://noticias.uol.com.br"
  },
  {
    "id": "vejaabril",
    "name": "Veja",
    "flag": "🇧🇷",
    "country": "Brazil",
    "city": "São Paulo",
    "lat": -23.65,
    "lon": -46.6,
    "lean": "right",
    "lang": "pt",
    "rssUrl": "https://veja.abril.com.br/feed/",
    "website": "https://veja.abril.com.br"
  },
  {
    "id": "kyivindependent",
    "name": "Kyiv Independent",
    "flag": "🇺🇦",
    "country": "Ukraine",
    "city": "Kyiv",
    "lat": 50.45,
    "lon": 30.52,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://kyivindependent.com/rss/",
    "website": "https://kyivindependent.com"
  },
  {
    "id": "pravdaua",
    "name": "Ukrayinska Pravda",
    "flag": "🇺🇦",
    "country": "Ukraine",
    "city": "Kyiv",
    "lat": 50.43,
    "lon": 30.54,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.pravda.com.ua/rss/",
    "website": "https://www.pravda.com.ua"
  },
  {
    "id": "ukrinform",
    "name": "Ukrinform",
    "flag": "🇺🇦",
    "country": "Ukraine",
    "city": "Kyiv",
    "lat": 50.46,
    "lon": 30.51,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://www.ukrinform.net/rss/",
    "website": "https://www.ukrinform.net"
  },
  {
    "id": "interfax_ua",
    "name": "Interfax-Ukraine",
    "flag": "🇺🇦",
    "country": "Ukraine",
    "city": "Kyiv",
    "lat": 50.47,
    "lon": 30.49,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://en.interfax.com.ua/news/general/rss",
    "website": "https://en.interfax.com.ua"
  },
  {
    "id": "euromaidan",
    "name": "Euromaidan Press",
    "flag": "🇺🇦",
    "country": "Ukraine",
    "city": "Kyiv",
    "lat": 50.42,
    "lon": 30.56,
    "lean": "center",
    "lang": "en",
    "rssUrl": "https://euromaidanpress.com/feed/",
    "website": "https://euromaidanpress.com"
  }
];

module.exports = sources;
